import Head from "next/head"
import Image from "next/image"
// Assests
import { AiFillPlayCircle } from "react-icons/ai"
import { FaUserAlt } from "react-icons/fa"
import ImageCourse from "../../assets/images/new-course.jpg"
// Styled components
import { Main } from "../../styles/carrito.styled"
import { SlidersTrailer } from "../../components/Sliders/Sliders.styled"
// Components
import { Header, Typography, SideNav, Input, Button } from "../../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  sessionVerificationNotCreated,
} from "../../../lib/session"
import { MdDelete } from "react-icons/md"

export default function Carrito() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav />
        <Header />

        <div className="content-page">
          <Typography text="Carrito" variant="H1" />

          <div className="items-carrito">
            <div className="item-carrito">
              <div className="flex">
                <Image className="image" src={ImageCourse} alt="" />

                <div className="content">
                  <Typography
                    text="Los pilares de la vida saludable"
                    variant="H3"
                  />

                  <div className="autor">
                    <FaUserAlt className="icon" />
                    <Typography text="Carlos jaramillo" variant="H4" />
                  </div>
                  <Typography text="$30.000" variant="H5" />
                </div>
              </div>

              <div className="delete">
                <MdDelete className="icon" />
              </div>
            </div>
          </div>
          <div className="total">
            <Typography text="Total: $30.000" variant="H2" />
          </div>
          <div className="divider"></div>
          <div className="form">
            <div>
              <Typography text="Datos de pago" variant="H4" />
              <br />
              <Input type="email" label="Nomber" name="nomber" />
              <Input type="email" label="Email" name="email" />
              <Input type="email" label="Telefono" name="phone" />
            </div>
            <div>
              <Typography text="Datos de tarjeta" variant="H4" />
              <br />
              <Input type="email" label="Numero de tarjeta" name="nomber" />
              <Input type="email" label="CV" name="nomber" />
            </div>
          </div>
          <Button text="Aceptar" bg color="redPrimary" />
        </div>
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  sessionVerificationNotCreated,
  sessionOptions
)
