import Head from "next/head"
import Image from "next/image"
import { useState, useEffect } from "react"
// Assests
import ImageCourse from "../../assets/images/new-course.jpg"
// Styled components
import { Main } from "../../styles/categorias.styled"
// Components
import { Header, Typography, SideNav } from "../../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  sessionVerificationNotCreated,
} from "../../../lib/session"
import { UserApi } from "../api"

const items = [1, 2, 3, 4]
const UserApiModel = new UserApi()

export default function Login() {
  const [topics, setTopics] = useState([])
  useEffect(() => {
    ;(async () => {
      const response = await UserApiModel.GetCategories()
      response.status === 200 && setTopics(response.data)
    })()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav />
        <Header />

        <div className="content-page">
          <Typography text="Categorías" variant="H1" />
          <br />
          <br />
          <br />
          <div className="category-list">
            {topics.map((item: any, index) => (
              <section key={index} className="category-item">
                <Image
                  className="category-image"
                  src={item.image}
                  alt=""
                  height={100}
                  width={100}
                />
              </section>
            ))}
          </div>
        </div>
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  sessionVerificationNotCreated,
  sessionOptions
)
