import Head from "next/head"
// Assests
import { AiFillPlayCircle } from "react-icons/ai"
import { FaUserAlt } from "react-icons/fa"
// Styled components
import { Main } from "../../styles/perfil.styled"
import { SlidersTrailer } from "../../components/Sliders/Sliders.styled"
// Components
import { Header, Typography, SideNav, Input, Button } from "../../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  sessionVerificationNotCreated,
} from "../../../lib/session"

export default function Perfil() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav />
        <Header />

        <div className="content-page">
          <Typography text="Perfil" variant="H1" />
          <br />
          <br />
          <br />
          <Input type="email" label="Nomber" name="nomber" />
          <Input type="email" label="Email" name="email" />
          <Input type="email" label="Telefono" name="phone" />
          <Input type="email" label="País" name="coutry" />
          <Input type="email" label="Ciudad" name="city" />
          <br />
          <br />
          <Button text="Aceptar" bg color="redPrimary" />
        </div>
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  sessionVerificationNotCreated,
  sessionOptions
)
