import Head from "next/head"
// Assests
import { AiFillPlayCircle } from "react-icons/ai"
import { FaUserAlt } from "react-icons/fa"
// Styled components
import { Main } from "../../styles/trailers.styled"
import { SlidersTrailer } from "../../components/Sliders/Sliders.styled"
// Components
import { Header, Typography, SideNav } from "../../components"

const items = [1, 2, 3, 4]

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav />
        <Header />

        <div className="content-page">
          <Typography text="Trailers" variant="H1" />

          <div className="my-courses-list">
            {items.map((item, index) => (
              <div key={index} className="course-item">
                <SlidersTrailer>
                  <div className="video-contain">
                    <video
                      className="video"
                      src="https://joy1.videvo.net/videvo_files/video/free/video0455/large_watermarked/_import_609113a1be0e89.39394997_preview.mp4"
                    ></video>
                    <AiFillPlayCircle className="icon-play" size={80} />
                  </div>
                  <div className="slider-content">
                    <h3>Nombre del curso</h3>
                    <div className="autor">
                      <FaUserAlt className="icon" />
                      <span>Carlos Jaramillo</span>
                    </div>
                  </div>
                </SlidersTrailer>
              </div>
            ))}
          </div>
        </div>
      </Main>
    </>
  )
}
