import Head from "next/head"
import { useRouter } from "next/router"
// Styled components
import { Main } from "../styles/politicas.styled"
// Components
import { Typography, SideNav, Header } from "../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  getSessionVerificationNotCreated,
} from "../../lib/session"

export default function Home(props: any) {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Ambly</title>
        <meta name="description" content="Generated by Ambly" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav minimal={!props.user} />
        <Header minimal={!props.user} />
        <div className="contain-page">
          <Typography variant="H4" text="About Ambly" />
          <br />
          <br />
          <Typography
            variant="P"
            text="
            Ambly te da la entrada a la mente brillante de destacadas personalidades en diferentes categorías como: negocios, estilo de vida, bienestar, arte y comunicación. 
            Estamos para inspirar tu vida y hacer que cada paso que das impacte de manera positiva nuestro planeta. 
            Buscamos amplificar la voz de aquellos expertos con una experiencia excepcional, que desde su perspectiva humana y única te brindarán la guía que ningún robot podría darte.
            Democratizar el conocimiento y la información que no se puede conseguir gratis y dártela es un reto que asumimos y estamos dispuestos a cumplir.
            "
          />
          <br />
          <Typography
            variant="P"
            text="
            El conocimiento que es un regalo de los cielos que debe ser democratizado. 
            "
          />
          <br />
          <Typography variant="H4" text="Ambly team" />
        </div>
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  getSessionVerificationNotCreated,
  sessionOptions
)
