import Head from "next/head"
// Styled components
import { Main } from "../styles/perfil.styled"
import { useRouter } from "next/router"
// Components
import { Header, SideNav, Button, Footer } from "../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  sessionVerificationNotCreated,
} from "../../lib/session"
import { useEffect, useState } from "react"

export default function Perfil(props: any) {
  const [message, setMessage] = useState('')
  const router = useRouter()
  

  const { extra1, extra2, transactionState }: any = router.query

  useEffect(() => {
    validateTransaction()
  }, [])
  
//Función para validar el estado de la transacción y mostrarselo al usuario
  const validateTransaction = () => {
    if (transactionState == 4) {
      setMessage('¡Tu compra se realizó con exito!')
    }
    else if (transactionState == 6) {
      setMessage('No se pudo realizar su compra')
    }
    else if (transactionState == 7) {
      setMessage('Pago pendiente')
    }
    else {
      setMessage('Hubo un error al realizar su compra')
    }
  }

  return (
    <>
      <Head>
        <title>Ambly</title>
        <meta name="description" content="Generated by Ambly" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav />
        <Header />

        <div
          className="content-page"
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            paddingTop: "10em",
            paddingBottom: "10em",
          }}
        >
          <h1>{message}</h1>
          <div style={{ marginTop: "3rem" }}>
            <Button
              text="Ir a mis cursos"
              color="redPrimary"
              bg
              onClick={() => router.push(`/mis-cursos`)}
            />
          </div>
        </div>
        <Footer />
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  sessionVerificationNotCreated,
  sessionOptions
)
