import Head from "next/head"
// Styled components
import { Main } from "../styles/perfil.styled"
import { useRouter } from "next/router"
// Components
import { Header, SideNav, Button, Footer } from "../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  sessionVerificationNotCreated,
} from "../../lib/session"

export default function Perfil(props: any) {
  const router = useRouter()

  const { extra1, extra2 }: any = router.query

  return (
    <>
      <Head>
        <title>Ambly</title>
        <meta name="description" content="Generated by Ambly" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav />
        <Header />

        <div
          className="content-page"
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            paddingTop: "10em",
            paddingBottom: "10em",
          }}
        >
          <h1>¡Tu compra se realizó con exito!</h1>
          <div style={{ marginTop: "3rem" }}>
            <Button
              text="Ir a mis cursos"
              color="redPrimary"
              bg
              onClick={() => router.push(`/mis-cursos`)}
            />
          </div>
        </div>
        <Footer />
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  sessionVerificationNotCreated,
  sessionOptions
)
