import { Main } from '@/styles/homeCourse.styled'
import Head from 'next/head'
import React from 'react'
import manReflexive from '../assets/images/back-man.jpg'
import manBlue from '../assets/images/manBlue.webp'
import Image from 'next/image'
import { Header, SideNav, Loader, Footer } from "../components"


const homeCourse = (props: any) => {
    return (
        <>
            <Head>
                <title>Ambly</title>
                <meta name="description" content="Generated by Ambly" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main>
                <SideNav minimal={!props.user} />
                <Header minimal={!props.user} />
                <article className='container'>
                    <div className='title'>
                        <article className='bars left'>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </article>
                        <h1>APRENDE. <br />INSPÍRATE. <br />VUELA.</h1>
                        <article className='bars'>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </article>
                    </div>
                    <Image
                        className="image"
                        src={manReflexive}
                        height={400}
                        width={500}
                        alt="manBlue"
                    />
                    <h2>APRENDE DE LOS MEJORES. INSPÍRATE POR SU EXPERIENCIA. VUELA SIN LÍMITES</h2>
                    <div className='title'>
                        <article className='bars left'>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </article>
                        <p>AMBLY HACE HONOR A LA EXPERIENCIA DE LAS GRANDES MENTES LATINAS.</p>
                        <article className='bars'>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </article>
                    </div>
                    <figure className='card'>
                        <Image
                            className="image"
                            src={manBlue}
                            height={210}
                            width={500}
                            alt=""
                        />
                        <figcaption>
                            <p>CONOCE LA CLASE <br /> AMBLY <span>00</span>1: <br /> "HACKEA TU CEREBRO"</p>
                            <a href='#'>Ingresa</a>
                        </figcaption>
                    </figure>
                    <p>SOMOS, PERTENECEMOS Y TENEMOS EL PODER DE ALCANZAR CUALQUIER CIMA.</p>
                    
                    <div className="title">
                        <article className='bars left'>
                                <div></div>
                                <div></div>
                                <div></div>
                                <div></div>
                            </article>
                        <p>¿Quieres ser el primero en saber sobre nuestros próximos lanzamientos?</p>
                        <article className='bars'>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div></div>
                        </article>
                    </div>

                    <form>
                        <small>REGISTRATE AQUÍ:</small>
                        <label>
                            Nombre
                            <input type="text" />
                        </label>
                        <label>
                            Correo electrónico
                            <input type="text" />
                        </label>
                        <label>
                            Teléfono
                            <input type="text" />
                        </label>
                        <button type='submit'>Enviar</button>
                    </form>
                </article>
            <Footer />
            </Main>
        </>
    )
}

export default homeCourse