import { useState, useEffect } from "react"
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
// Styled components
import { Main } from "../styles/inicio.styled"
// Components
import {
  Header,
  Sliders,
  HeaderSection,
  Typography,
  SideNav,
  Modal,
  Loader,
  Footer,
} from "../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  getSessionVerificationNotCreated,
} from "../../lib/session"
import { UserApi, CourseApi, InstructorApi, TrailersApi } from "./api"
// Store
import { useAppDispatch } from "../store"
import { loadCourses } from "../store/User/actions"
import { useRouter } from "next/router"
const items = [1, 2, 3, 4]

const UserApiModel = new UserApi()
const CourseApiModel = new CourseApi()
const InstructorApiModel = new InstructorApi()
const TrailersApiModel = new TrailersApi()

export default function Login(props: any) {
  const dispatch = useAppDispatch()
  const router = useRouter()

  const [loading, setLoading] = useState(false)

  const [coursesList, setCourseslist] = useState([])
  const [intructorList, setIntructorList] = useState([])
  const [trailersList, setTrailerList] = useState([])
  const [topics, setTopics] = useState([])
  const [showModal, setShowModal] = useState(false)
  const [trailerPlay, setTrailerPlay] = useState({
    title: "",
    video: "",
  })

  const handleTrailerClick = (item: any) => {
    setTrailerPlay({
      title: item.title,
      video: item.video,
    })
    setShowModal(true)
  }

  useEffect(() => {
    setLoading(true)
    ;(async () => {
      if (props.user && props.user.id) {
        const response = await UserApiModel.GetMyCourses(props.user.id)
        response.status === 200 && dispatch(loadCourses(response.data.courses))
      }
    })()
    ;(async () => {
      const response = await CourseApiModel.GetCourses()
      response.status === 200 && setCourseslist(response.data)
    })()
    ;(async () => {
      const response = await InstructorApiModel.GetInstructors()
      response.status === 200 && setIntructorList(response.data)
    })()
    ;(async () => {
      const response = await TrailersApiModel.GetTrailers()
      response.status === 200 && setTrailerList(response.data)
    })()
    ;(async () => {
      const response = await UserApiModel.GetCategories()
      response.status === 200 && setTopics(response.data)
    })()
    setTimeout(() => {
      setLoading(false)
    }, 1000)
  }, [props.user, dispatch])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Loader loading={loading} />
        <Modal
          show={showModal}
          onClose={() => setShowModal(false)}
          title={trailerPlay.title}
        >
          {showModal && (
            <video
              className="page-top-video"
              controls
              style={{ width: "100%" }}
              src={trailerPlay.video}
            ></video>
          )}
        </Modal>
        <SideNav minimal={!props.user} />
        <Header minimal={!props.user} />
        <div className="content-page-top">
          <Sliders variant="new" items={coursesList} />
        </div>
        <div className="content-page">
          <Typography
            text={
              '"Explore your new skill today explore your new skill today explore your new skill today"'
            }
            variant="H1"
            style={{ textAlign: "center" }}
          />
          <div>
            <HeaderSection
              title="Populares"
              action={() => router.push(`/usuario/cursos/todos`)}
            />
            <Sliders
              variant="popular"
              items={[
                coursesList[0],
                coursesList[1],
                coursesList[0],
                coursesList[1],
              ]}
            />
          </div>

          <div>
            <HeaderSection
              title="Trailers"
              action={() => router.push(`/usuario/trailers`)}
            />
            <Sliders
              variant="trailers"
              onClickSlider={(data) => handleTrailerClick(data)}
              items={[
                trailersList[0],
                trailersList[0],
                trailersList[0],
                trailersList[0],
              ]}
            />
          </div>

          <div>
            <HeaderSection
              title="Maestros"
              action={() => router.push(`/usuario/maestros`)}
            />

            <div className="teachers-list">
              {intructorList
                .concat([intructorList[0], intructorList[1], intructorList[2]])
                .map((item: any, index) => (
                  <Link
                    href={`/usuario/maestro/${item?.id}`}
                    key={index}
                    className="teacher-item"
                  >
                    <Image
                      className="teacher-image"
                      src={item?.image_secondary}
                      alt=""
                      height={100}
                      width={100}
                    />
                    <Typography
                      className="teacher-title"
                      text={item?.name_instructor}
                      variant="H4"
                    />
                  </Link>
                ))}
            </div>
          </div>

          <div>
            <HeaderSection title="Categorías" />
            <div className="category-list">
              {topics.map((item: any, index) => (
                <Link
                  href={`/usuario/cursos/todos`}
                  key={index}
                  className="category-item"
                >
                  <Image
                    className="category-image"
                    src={item.image}
                    alt=""
                    height={100}
                    width={100}
                  />
                </Link>
              ))}
            </div>
          </div>
        </div>
        <Footer />
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  getSessionVerificationNotCreated,
  sessionOptions
)
