import Head from "next/head"

// Styled components
import { Main } from "../styles/login.styled"
import { IoMdArrowBack } from "react-icons/io";
import LoginForm from "@/components/Login/loginForm";

//Hooks
import { withIronSessionSsr } from "iron-session/next"
import { sessionOptions, sessionVerificationCreated } from "../../lib/session"
import { Typography } from "@/components";


const handleGoBack = () => {
  window.history.back()
}

export default function Login() {

  return (
    <>
      <Head>
        <title>Ambly</title>
        <meta name="description" content="Generated by Ambly" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <IoMdArrowBack className="iconBack" onClick={handleGoBack} />
        <LoginForm setShowLogin={false} useLinkForRegisterPage={true}/>
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  sessionVerificationCreated,
  sessionOptions
)