
import Head from "next/head"
import { IoMdArrowBack } from "react-icons/io";

// Styled components
import { Main } from "../styles/login.styled"
// Components
import Register from "@/components/Login/register";

//Hooks
import { sessionOptions, sessionVerificationCreated } from "../../lib/session"
import { withIronSessionSsr } from "iron-session/next"

const handleGoBack = () => {
  window.history.back()
}

export default function Registro() {
  return (
    <>
      <Head>
        <title>Ambly</title>
        <meta name="description" content="Generated by Ambly" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <IoMdArrowBack className="iconBack"
        onClick={handleGoBack}  
        />
        <Register setShowLogin={false} useLinkForRegisterPage={true}/>
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  sessionVerificationCreated,
  sessionOptions
)