import Head from "next/head"
import { useRouter } from "next/router"
// Styled components
import { Main } from "../styles/politicas.styled"
// Components
import { Typography, SideNav, Header } from "../components"
import { withIronSessionSsr } from "iron-session/next"
import {
  sessionOptions,
  getSessionVerificationNotCreated,
} from "../../lib/session"
import Link from "next/link"

export default function Home(props: any) {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Ambly</title>
        <meta name="description" content="Generated by Ambly" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav minimal={!props.user} />
        <Header minimal={!props.user} />
        <div className="contain-page">
          <Typography variant="H1" text="Términos de Servicio de Ambly.co" />
          <br />
          <p>Bortek SAS le dan la bienvenida a Ambly.co (en adelante la "Compañía", "Nosotros"). Nos complace ofrecerle acceso al Servicio (como se define más abajo), sujeto a estos términos y condiciones (los "Términos de Servicio") y a la <Link href="/politicas">Política de Privacidad</Link> correspondiente de Ambly.co. Al acceder y utilizar el Servicio, usted expresa su consentimiento, acuerdo y entendimiento de los Términos de Servicio y la Política de Privacidad. Si no está de acuerdo con los Términos de Servicio o la Política de Privacidad, abandone la página web.</p>
          <br />
          <ol>
            <li>
              <Typography variant="H3" text="Generalidades sobre los Términos de Servicio." />
              <br />
              <ol>
                <li><Typography variant="P" text="El Servicio es ofrecido por Bortek S.A.S., identificado con NIT 901.587.150-4" /></li>
                <br />
                <li><Typography variant="P" text="Las Compañía posee y opera el sitio Ambly.co., El usuario tendrá la posibilidad de aprender diversos temas de bienestar, estilo de vida, negocios, comunicación y arte a través de nuestros servicios en línea (plataforma educativa, chat, streamings, podcast, audiolibros etc.) y de la funcionalidad del sitio." /></li>
                <br />
                <li><Typography variant="P" text="Lo siguiente, es un breve resumen de determinados términos y condiciones que se incluyen en estos Términos de Servicio. “El Servicio” se entenderá como cualquier uso de forma gratuita o paga de la página web Ambly.co." /></li>
              </ol>
              <br />
              <Typography
                variant="P"
                text='No obstante, este resumen se proporciona únicamente para su comodidad; por lo tanto, usted debería leer todos los Términos de Servicio para hacer uso de esta página.'
              />
              <br />
              <ol start={4}>
                <li><Typography variant="P" text="El Servicio sólo funciona con su computadora personal, móvil personal, tableta personal y dispositivos compatibles." /></li>
                <br />
                <li><Typography variant="P" text="Para utilizar el Servicio, deberá registrarse y abrir una Cuenta de Ambly.co." /></li>
                <br />
                <li><Typography variant="P" text="Nos reservamos el derecho a realizar actualizaciones, modificaciones y supresiones periódicas del Servicio, con o sin previo aviso." /></li>
                <br />
                <li><Typography variant="P" text="El Servicio incluye funciones relacionadas con la seguridad y la manipulación indebida que, en caso de activarse, podrían ocasionar que el contenido previamente disponible para su uso, deje de estarlo a partir de entonces." /></li>
                <br />
                <li><Typography variant="P" text="El usuario debe tener al menos 18 años de edad para aceptar estos Términos de Servicio, quedando entendido, que si fuera menor de 18 años, su padre o tutor legal puede aceptarlos en su nombre." /></li>
                <br />
                <li><Typography variant="P" text="Al utilizar el Servicio, usted autoriza la recopilación, procesamiento y utilización de toda aquella información relacionada con el uso que usted hace del Servicio, la cual se recopila y maneja de conformidad con los términos de nuestra Política de Privacidad. Usted comprende que tiene el derecho de solicitar la supresión de sus datos." /></li>
                <br />
                <li><Typography variant="P" text="Nos reservamos el derecho, a nuestra discreción, de cambiar estos Términos de Servicio en cualquier momento, sin previo aviso. En caso de algún cambio sustancial, haremos todos los esfuerzos comercialmente razonables para notificárselo y obtener su consentimiento antes de implementar dichos cambios." /></li>
                <br />
                <li><Typography variant="P" text="La información relacionada con los plazos de validez de las ofertas y la disponibilidad de los productos y/o servicios, así como los tiempos de entrega y el precio total, se encuentra disponible en Ambly.co." /></li>
                <br />
                <li><Typography variant="P" text="Bortek SAS renuncia, en la máxima medida permitida por la ley, a determinadas declaraciones y garantías relacionadas con el Servicio, y limita su responsabilidad con respecto a las mismas." /></li>
                <br />
                <li>
                  <Typography variant="P" text="Si tiene alguna pregunta acerca de estos Términos de Servicio, o desea comunicarse con nosotros por cualquier razón, escriba a:" />
                  <br />
                  <ul>
                    <li><Typography variant="P" text="Bortek S.AS., con domicilio en Calle 86 #20-45. o envíe un mensaje electrónico a at@ambly.co " /></li><br />
                  </ul>
                </li>
              </ol>
            </li> 

            <li>
              <Typography variant="H3" text="Permiso para utilizar el Servicio; reserva de derechos." />
              <br />
              <Typography
                variant="P"
                text='Al aceptar estos Términos de Servicio, se le concede a usted un derecho limitado, no exclusivo, intransferible y no sub-licenciable, para entrar, acceder y utilizar el Servicio exclusivamente para uso personal y no comercial. Todos los derechos que no se le conceden expresamente a usted en estos Términos de Servicio, están reservados por la Compañía y sus licenciadores, según corresponda. Usted acepta que este permiso es para su uso personal, no comercial y que nadie más que usted va a utilizar el Servicio. Usted no tiene derechos para copiar o reproducir en todo o en parte alguna porción del Servicio, incluyendo sin que ello implique limitación alguna, el contenido de Ambly.co. Aparte de la licencia limitada que se otorga en la Sección 2, usted no tiene ningún otro derecho, título ni participación en el Servicio. Usted entiende y reconoce que, en todas las circunstancias, sus derechos con respecto al Servicio estarán limitados por los derechos de autor o las leyes de propiedad intelectual pertinentes y los presentes Términos de Servicio.'
              />
            </li> 
            <br />
            <li>
              <Typography variant="H3" text="Descripción del Servicio." />
              <br />
              <ol className="subtitle">
                <li className="subtitle-li">
                  <Typography variant="H4" text="Generalidades:" />
                  <ul>
                    <li>
                      <Typography variant="H6" text="Su Cuenta e Información de Registro." />
                      <Typography variant="P" text="Puede navegar, previsualizar y realizar una búsqueda dentro del Servicio sin necesidad de abrir una Cuenta de Ambly.co, ni de suministrar información de registro. Sin embargo, para cualquier otro uso del Servicio y el acceso al contenido de Ambly.co, deberá abrir una cuenta y facilitar la información de registro a la Compañía." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Acceso al Contenido de Ambly.co." />
                      <Typography variant="P" text="La propiedad sobre el contenido de Ambly.co se define más adelante en la Sección 8 (Propiedad Intelectual) de los presentes Términos de Servicio. Usted puede acceder al contenido de Ambly.co la cantidad de veces que lo desee siempre que se haya suscrito al Servicio. También está autorizado a transferir los podcasts de Ambly.co a determinados dispositivos portátiles para uso personal y no comercial.
                      Por otra parte, puede grabar podcasts de Ambly.co en CD o DVD para uso personal y no comercial. Sin embargo, una vez que haya transferido y/o grabado el Contenido de Ambly.co en dicho medio, usted conviene en no copiar, reproducir, distribuir ni transferir dicho contenido a ningún otro medio o dispositivo, ni distribuirlo o transferirlo a cualquier otra persona o tercero. Las funciones de grabación y transferencia del Contenido de Ambly.co son exclusivamente para su comodidad y no constituirán una concesión o renuncia (u otra limitación o implicación) de cualquier derecho de los titulares de los derechos de autor del Contenido de Ambly.co, inclusive cualquier composición musical en el mismo.
                      " />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Términos adicionales del software y hardware." />
                      <Typography variant="P" text="Tenga en cuenta que tal vez existan acuerdos de licencia del usuario final y términos de servicio por separado que deba aceptar para el hardware y el software que utilice en relación con el Servicio, o que pueda interactuar con el Servicio. Su negativa a aceptar los términos de dichos acuerdos limitaría su capacidad para utilizar plenamente el Servicio. Además, el Servicio sólo funciona con dispositivos compatibles." />
                    </li>
                    <br />
                  </ul>
                </li>

                <li className="subtitle-li">
                  <Typography variant="H4" text="Promociones y Garantía." />
                  <ul>
                    <li>
                      <Typography variant="H6" text="Promociones." />
                      <Typography variant="P" text="La Compañía, otras entidades de Ambly.co y determinados terceros pueden, de vez en cuando, colocar anuncios publicitarios o presentar ofertas y materiales promocionales en o a través del Servicio. Su participación en cualquier promoción u oferta está sujeta a las normas aplicables relacionadas con la promoción. Sus relaciones con otras entidades o terceros, así como su participación en promociones u ofertas de terceros que se anuncian o aparecen en el Servicio son exclusivamente entre usted y dicho tercero. Tenga en cuenta que debe tener al menos 18 años de edad para participar en cualquier promoción u oferta que tenga conexión o guarde relación de alguna manera con el Servicio. Usted acepta que la compañía no será responsable de ningún tipo de daño o pérdida que surja como resultado de tales relaciones o de la presencia de dichos anunciantes en el servicio." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Plazos de validez." />
                      <Typography variant="P" text="La información suministrada en Ambly.co en relación a los plazos de validez de las ofertas se podrá encontrar disponible en Ambly.co. En caso de que no se encuentre expresamente establecido el plazo de validez, se entenderá que es de cinco (5) días calendario." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Disponibilidad." />
                      <Typography variant="P" text="La disponibilidad de los productos y/o servicios, al igual que el catálogo y los tiempos de entrega ofertados puede ser visitado en Ambly.co." />
                      <br />
                    </li>
                  </ul>
                </li>

                <li className="subtitle-li">
                  <Typography variant="H4" text="Restricciones." />
                  <Typography variant="P" text="El uso del Servicio, por parte de usted, está sujeto a las siguientes restricciones:"/>
                  <ul>
                    <li>
                      <Typography variant="H6" text="Normas y políticas de la Compañía. " />
                      <Typography variant="P" text='Al utilizar el Servicio, usted estará sujeto a cualquier otra directriz o norma aplicable a los servicios y características específicas que se publiquen en forma ocasional (las "Directrices"). Todas las Directrices se incorporan mediante referencia a estos Términos de Servicio.'/>
                      <br />
                      <Typography variant="P" text='Estas Directrices se aplicarán en forma general de manera no discriminatoria a todos los usuarios finales del Servicio y podrían incluir, por ejemplo, actualizaciones, modificaciones y reinstalaciones del software requeridas o automáticas, y la obtención de parches disponibles para, entre otras razones, abordar cuestiones de seguridad, interoperabilidad y/o funcionamiento. Estas actualizaciones, modificaciones y operaciones similares pueden realizarse en forma periódica o cuando sea necesario, sin previo aviso siempre que estos cambios no modifiquen de manera esencial el servicio o la utilización de sus datos personales.'/>
                      <br />
                      <Typography variant="P" text='Además, usted entiende que determinados aspectos del Servicio son capaces de controlarse a sí mismos y pueden crear un sistema especial de identificación con fines relacionados con la seguridad y la detección de manipulaciones indebidas. El acceso de usted a determinadas aplicaciones está sujeto a restricciones por motivos de seguridad o según las políticas de protección de Contenido de Ambly.co consistentemente aplicadas. Usted entiende y acepta que es probable que el Contenido de Ambly.co que anteriormente estaba disponible para su uso, no se encuentre disponible a partir de ese momento.'/>
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Requisito de edad." />
                      <Typography variant="P" text="Usted debe tener al menos 18 años de edad para convenir y aceptar estos Términos de Servicio en nombre propio. Si es menor de 18 años, su padre, madre o tutor legal debe aceptar estos Términos de Servicio y registrarse para el Servicio en nombre de usted." />
                      <br />
                      <Typography variant="P" text="Si es menor de edad, se le solicita que no proporcione información alguna a la Compañía, ya sea mediante el uso del Servicio, la participación en alguna de las promociones, concursos o sorteos relacionados con el Servicio, o a través de cualquier otra actividad." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Conducta prohibida." />
                      <Typography variant="P" text='Usted no utilizará el Servicio para transmitir, mostrar, ejecutar o de algún modo poner a disposición mensajes, contenidos o materiales (i) que sean ilegales, obscenos, amenazantes, masivos no solicitados o "spam", difamatorios, invasores de la privacidad, o (ii) que violen o infrinjan derechos de autor, marcas registradas, patentes, secretos comerciales y otros derechos de propiedad intelectual, derechos de privacidad o publicidad, reglamentos o estatutos de comunicaciones, o cualesquiera otras leyes, incluyendo, sin limitación, las leyes sobre difamación, acoso, obscenidad y pornografía; (iii) que constituyan campañas políticas o solicitudes de venta o marketing o que contengan virus informáticos u otro código de computadora destinado a interferir con la funcionalidad de los sistemas de computadoras, o (iv) que de alguna manera perjudiquen a los menores. Usted conviene en no interrumpir ni intentar interrumpir la operación o el Servicio de ninguna manera. Durante los Cursos, se espera que los estudiantes/usuarios se comporten de una manera adecuada y respetuosa, teniendo en cuenta un alto estándar de educación para con las otras personas con quienes pueda tener contacto por medio de la plataforma. Cualquier violación a lo aquí dispuesto, estará sujeta a la revisión y las acciones pertinentes que la Compañía decida adoptar, a su sola consideración e inclusive proceder al derecho de Terminar el Servicio de acuerdo a lo dispuesto en la Sección 9.3 del presente documento. Además, no podrá utilizar una dirección de correo electrónico falsa o de algún modo engañar a otros miembros en cuanto a su identidad o al origen de un mensaje o contenido.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Restricción sobre el uso relacionado con el Servicio." />
                      <Typography variant="P" text='El Servicio incluye componentes de seguridad por lo que se aplican normas y políticas especiales. Usted no deberá intentar (ni apoyar los intentos de otros) eludir, aplicar ingeniería inversa, descifrar, descompilar, desmontar o de algún modo modificar, alterar o interferir con ningún aspecto del Servicio. Usted no podrá distribuir, intercambiar, modificar, vender o revender, o transmitir a cualquier otra persona cualquier parte del Servicio, incluyendo, sin limitación, cualquier texto, imagen o audio, para cualquier propósito empresarial, comercial o público. Usted conviene en no copiar, vender, distribuir o de algún modo transferir Contenido de Ambly.co, salvo del modo expresamente permitido en el presente.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Restricción sobre el uso relacionado con la Cuenta de Ambly.co." />
                      <Typography variant="P" text='Usted solo puede abrir una cuenta de Ambly.co para usted mismo, y no para ninguna otra persona, con sujeción a las disposiciones de la sección anterior titulada "Requisitos de Edad". Usted acepta que no permitirá que otras personas utilicen la Información de Registro y/o la Cuenta de Ambly.co y acepta que usted es el único responsable de mantener la confidencialidad y seguridad de los mismos. Usted conviene en notificar inmediatamente a la Compañía cualquier uso no autorizado de su contraseña y/o Cuenta de Ambly.co, enviándonos un correo electrónico a at@ambly.co. Si utiliza o abre una cuenta en el Servicio en nombre de una empresa, entidad u organización (colectivamente "Organización Suscriptora"), entonces usted declara y garantiza que es un representante autorizado de dicha Organización Suscriptora con autoridad para obligar a tal organización a estos Términos de Servicio, y acuerda obligarse por estos Términos de Servicio en nombre de dicha Organización Suscriptora.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Restricción sobre el uso relacionado con el Contenido de Ambly.co." />
                      <Typography variant="P" text='Salvo del modo expresamente aquí permitido, los derechos concedidos a usted en virtud del presente no le confieren ninguno de los siguientes: (a) derechos de reproducción o uso promocional en el Contenido de Ambly.co, (b) derechos de celebrar acuerdos con cualquier sistema de difusión que genere ingresos (terrestre, satelital, cable y/u otros canales de distribución), (c) derechos de distribuir o redistribuir el Contenido de Ambly.co en aplicaciones de streaming (vía Internet, intranets y/u otras redes), (d) derechos de distribuir a otras personas el Contenido de Ambly.co en otros sistemas de distribución de contenido (aplicaciones de audio de pago o audio bajo demanda, etc.) o en medios físicos (discos compactos, discos digitales versátiles, chips semiconductores, discos duros, tarjetas de memoria y similares), o (e ) derechos de uso comercial, venta, reventa, reproducción, distribución o promocional para el Contenido de Ambly.co. Cualquier solución de gestión de derechos digitales que se proporciona con el Contenido de Ambly.co es una parte inseparable del mismo, y no podrá eludirse, salvo en la medida permitida por la ley aplicable. Si usted está en posesión o control de Contenido de Ambly.co, es su responsabilidad no perder, destruir ni dañar dicho contenido.' />
                      <br />
                    </li>
                  </ul>
                </li>


                <li className="subtitle-li">
                  <Typography variant="H4" text="Cargos y facturación." />
                  <ul>
                    <li>
                      <Typography variant="H6" text="Acuerdo de pago." />
                      <p>Usted acepta pagar por todo el Contenido de <a target="_blank" href="https://ambly.co/">Ambly.co</a> a menos que le haya sido ofrecido en forma gratuita.</p>
                      <br />
                      <Typography variant="P" text="El Usuario otorga su consentimiento para que Ambly comience la prestación de El Servicio pactado una vez reciba la confirmación del pago." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Precio total." />
                      <Typography variant="P" text="El Servicio ofertado en Ambly.co incluye todos los impuestos, costos y gastos que deba pagar el consumidor para adquirirlo. Por lo cual el Usuario debe revisar el precio antes de proceder al pago." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Pago a Cuotas." />
                      <Typography variant="P" text='En caso de que Ambly ofrezca la adquisición de Servicio mediante pago a cuotas y el Usuario opte por esta modalidad, el Usuario entiende y acepta que:' />
                      <br />
                      <Typography variant="P" text='(i) si realiza el pago con tarjeta de crédito otorga autorización para que Ambly realice el débito automático, mensual, recurrente que será descontado mes a mes durante los meses que corresponda hasta completar el pago total por los Servicios según el plan o producto adquirido. El Usuario se compromete a mantener el cupo disponible necesario para que sea realizado el cobro en las fechas y por los montos correspondientes.' />
                      <br />
                      <Typography variant="P" text='(ii) Si realiza el primer pago mediante un medio diferente a tarjeta de crédito. El Usuario se obliga a realizar el pago directo de la cuota correspondiente, de forma mensual, durante los primeros cinco días del mes por el número de meses autorizado por Ambly, hasta completar el pago total por El Servicio.' />
                      <br />
                    </li>
                  </ul>
                </li>
                <li className="subtitle-li">
                  <p>En caso de adquirir algún plan con Ambly.co, el enlace con la opción de pago seleccionada por usted en el primer pago será enviado por correo electrónico mes a mes con antelación a la fecha límite y usted se compromete a enviar el respectivo comprobante de pago a <a href="mailto:at@ambly.co">at@ambly.co</a> para mantener activa la suscripción dentro de los primeros cinco días del mes.</p>
                </li>
                <li className="subtitle-li">
                  <p><b>Intentos de cobro y cancelación por no pago:</b> En caso de adquirir algún plan que requiera pago mensual, al no ser exitoso el débito automático, Ambly realizará dos intentos de cobro adicionales, en caso de que no pueda realizarse el débito se entenderá desistido el acuerdo por parte de el Usuario y Ambly procederá a la cancelación de El Servicio. En los casos de pago mediante medios distintos a tarjeta de crédito, el desistimiento de El Servicio se dará cuando el Usuario no reporte el pago máximo cinco días después de la fecha límite de pago de cada cuota.</p>
                </li>
                <li className="subtitle-li">
                  <Typography variant="P" text='En caso de adquirir algún plan de pago mensual, el usuario reconoce que no habrá lugar a devoluciones o reembolsos de ningún tipo luego del desistimiento por incumplimiento en el pago.' />
                  <br />
                  <ul>
                    <li>
                      <Typography variant="H6" text="Renovación automática." />
                      <Typography variant="P" text='En caso de adquirir un plan dentro de la opción de servicios y productos de Ambly, los planes se renuevan automáticamente. El Usuario acepta que la renovación del Servicio se dé automáticamente por el mismo periodo inicialmente contratado.' />
                      <br />
                      <Typography variant="P" text='Para tal efecto, Ambly realizará el débito de la renovación en una sola cuota con independencia del número de cuotas en que se hubiere diferido el pago al momento de la suscripción, para lo cual el Usuario expresamente autoriza a Ambly a debitar y hacer cargos a cualquiera de las formas de pago asociadas a su cuenta para la adquisición de El Servicio y sus renovaciones. Ambly se reserva el derecho de designar a terceros para efectos de realizar el cobro.' />
                      <br />
                      <Typography variant="P" text='Una vez Ambly verifique que el pago ha sido exitoso se procede con la activación de El Servicio.' />
                      <br />
                      <p>Si el usuario no desea renovar El Servicio puede gestionar directamente la no renovación , por medio de la plataforma, mediante correo electrónico a <a href="mailto:at@ambly.co">at@ambly.co</a> o cualquiera de los canales habilitados por Ambly por lo menos 5 días antes del vencimiento de El Servicio.</p>
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Derecho de retracto." />
                      <p>Los únicos Servicios ofrecidos por Ambly, a los que le son aplicables el derecho de retracto son los bonos de regalo, respecto de los cuales el Usuario podrá retractarse de su compra en los términos de Ley siempre que no haya realizado la activación del bono, momento a partir del cual se entenderá que comenzó la ejecución del Servicio. Dicho derecho podrá ejercerse mediante comunicación a <a href="mailto:at@ambly.co">at@ambly.co</a></p>
                      <br />
                      <p>Respecto de cualquiera de los planes o productos adquiridos con pago único, no aplica el derecho de retracto, toda vez que desde el momento en que se realiza el pago inicia la ejecución de los Servicios con la puesta a disposición del material contenido en <a target="_blank" href="https://ambly.co/">Ambly.co</a></p>
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Terminación." />
                      <p>La Compañía se reserva el derecho a dar por terminada su Cuenta de <a target="_blank" href="https://ambly.co/">Ambly.co</a> y/o el acceso por parte de usted al Servicio si infringe los Términos de Servicio. Si se diera por terminada su membresía y suscripción(s) de <a target="_blank" href="https://ambly.co/">Ambly.co</a> al Servicio, no serán reembolsables las cuotas ni los cargos.</p>
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Impuestos." />
                      <Typography variant="P" text='Las compras en el Servicio pueden incluir el impuesto sobre ventas o el impuesto al valor agregado (cuando proceda) y dicho impuesto se basará en la mejor información disponible acerca de su dirección. En tales casos, se aplicará el tipo impositivo que esté en vigor en el momento en que se realicen las compras en el Servicio. Si cambia el tipo impositivo aplicable a las ventas antes de finalizar las compras correspondientes, se aplicará el nuevo tipo impositivo que esté en vigor en el momento de concretar la compra en el Servicio. Podrían aplicarse otras limitaciones y renuncias a la responsabilidad sobre productos y servicios. Usted será el único responsable de pagar la totalidad de dichos impuestos.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Derecho al cambio de precios." />
                      <Typography variant="P" text='Todos los precios relacionados con el Servicio están sujetos a cambios por la Compañía en cualquier momento, sin previo aviso y sin responsabilidad alguna hacia el Usuario. La Compañía no ofrece una protección de precios o reembolsos en caso de una caída de precios o una oferta promocional. Ambly presentará el precio total al momento de pagar.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Tarjetas de crédito o débito bimoneda." />
                      <p>El uso de tarjetas de crédito se sujetará a lo establecido y pactado por el emisor. específicamente a lo pactado en los respectivos Contratos de Apertura y Reglamento de Uso. Tratándose de tarjetas bancarias aceptadas en el portal <a target="_blank" href="https://ambly.co/">Ambly.co</a> los aspectos relativos a éstas, tales como la fecha de emisión, caducidad, cupo, bloqueos, entre otros, se regirán por el respectivo Contrato de Apertura y Reglamento de Uso.</p>
                      <br />
                      <p>Reversión a tarjeta de crédito: Los reembolsos que se realizan por este método podrán ser parciales o totales, según sea el caso. <a target="_blank" href="https://ambly.co/">Ambly.co</a> realizará la solicitud de reversión en la plataforma de pago para que ésta notifique al banco sobre la reversión del dinero. A partir de la confirmación de la solicitud, la entidad bancaria contará con los tiempos dispuestos según sus políticas internas. El Usuario deberá sujetarse a los términos de duración del proceso de aplicación estipulado por su banco.</p>
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Reembolsos" />
                      <Typography variant="P" text='Salvo disposición legal contraria, los pagos realizados no son reembolsables en ninguna circunstancia. En los casos excepcionales en los que sea procedente una devolución, Ambly informará el proceso a efectuar según el método de pago. El Usuario se obliga a suministrar la información solicitada por Ambly para poder proceder con el reembolso. Estos podrán ser parciales o totales, según sea el caso.' />
                      <br />
                      <Typography variant="P" text='El Usuario deberá sujetarse a los términos de duración del proceso de aplicación estipulados bien sea por su banco o por el Apple Store.' />
                    </li>
                  </ul>
                </li>
                <br />
                <li className="subtitle-li">
                  <Typography variant="H6" text="Notificaciones especiales." />
                  <Typography variant="P" text="Como usuario del Servicio, tenga en cuenta lo siguiente:" />
                  <ol>
                    <br />
                    <li>
                      <Typography variant="H6" text="Privacidad." />
                      <Typography variant="P" text="Al registrarse en el Servicio, usted otorga su consentimiento para la recopilación y procesamiento de toda la información relacionada con el uso que usted hace del Servicio, incluyendo la Información de Registro. La Compañía recopila y maneja esta información de conformidad con los términos de la Política de Privacidad, que queda expresamente incorporada en estos Términos de Servicio mediante referencia." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Exactitud de la información." />
                      <Typography variant="P" text="Usted declara y garantiza que toda la información (incluida la Información de Registro y las respuestas a los sondeos y encuestas) que proporciona a la Compañía es correcta, completa y vigente, y se compromete a mantenerla actualizada en todo momento. También admite que cualquier información proporcionada por usted a la Compañía no violará ninguna ley o reglamento, ni infringirá los derechos de terceros." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Certificación de residencia y capacidad para celebrar contratos." />
                      <Typography variant="P" text="Al abrir una Cuenta en el servicio de e-learning de Ambly.co, usted declara y garantiza a la Compañía que reside en el territorio que ha indicado en su perfil y que tiene capacidad para celebrar contratos de conformidad con las leyes de su jurisdicción." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Naturaleza del Contenido." />
                      <Typography variant="P" text="Usted entiende que al utilizar el Servicio y tener acceso al Contenido de Ambly.co, podrá encontrar materiales que puede considerar explícitos, ofensivos o de alguna manera objetables. La Compañía podrá incluir, si se encontrara disponible, información relacionada con calificaciones, tipo de contenido y descripciones, si los propietarios correspondientes del Contenido de Ambly.co proporcionaran dicha información. Sin embargo, la Compañía no es responsable de la exactitud de ese tipo de información. Usted conviene en lo siguiente, sin importar si el Servicio incluye o no incluye las funciones de control por parte de los padres y sin importar las veces que utiliza dichas funciones: (a) es su responsabilidad determinar qué Contenido de Ambly.co o qué materiales que integran el Servicio cumplen con sus estándares, y (b) bajo ninguna circunstancia, la Compañía o sus Afiliadas o proveedores de contenido serán de ninguna forma responsables de ningún Contenido de Ambly.co o materiales a los que usted tenga acceso. Usted acepta usar el Servicio a su propio riesgo y que la Compañía y sus Afiliadas no tendrán responsabilidad alguna frente a usted respecto a cualquier contenido o materiales que incluya el Servicio." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Riesgo de uso." />
                      <Typography variant="P" text="Ni la Compañía ni sus Afiliadas asumirán responsabilidad alguna y no serán responsables por ningún daño o virus que provoque algún daño a su computadora u otra propiedad como consecuencia del acceso, uso, descarga o navegación por el Servicio." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Enlaces de otros sitios Web a sitios de terceros; noticias RSS." />
                      <Typography variant="P" text="La Compañía no es responsable del contenido o la disponibilidad de las noticias en formato RSS ni de sitios web relacionados con el Servicio, ni tampoco lo es de sitios web de terceros que tengan enlaces hacia o desde el Servicio. El acceso por parte de usted a noticias RSS y enlaces a otros sitios Web queda a riego de usted por completo. Todas las noticias RSS y los enlaces se proporcionan únicamente para su comodidad y no deberán interpretarse como un aval del propietario/patrocinador del sitio. La Compañía renuncia a cualquier garantía, ya sea expresa o implícita, en cuanto a la exactitud, calidad o cualquier otro aspecto de cualquier material o información que contengan dichas noticias RSS y sitios Web." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="El derecho de la Compañía a cambiar estos Términos de Servicio." />
                      <Typography variant="P" text="La Compañía se reserva el derecho, a su discreción, de cambiar, modificar, añadir o eliminar partes de estos Términos de Servicio en cualquier momento, sin previo aviso a usted. Todos los cambios entrarán en vigor de inmediato. En caso de algún cambio sustancial, haremos todos los esfuerzos comercialmente razonables para notificárselo y obtener su consentimiento antes de implementar dichos cambios. Le recomendamos que consulte estos Términos de Servicio en forma periódica para ver si se han registrado cambios. El uso continuado del Servicio por parte suya después de la publicación de dichos cambios implica la aceptación de los mismos." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="El derecho de la Compañía a efectuar cambios al Servicio." />
                      <Typography variant="P" text="La Compañía puede agregar, cambiar, terminar, remover o suspender cualquier material incorporado al Servicio, incluyendo características, precios y especificaciones de los productos descritos o reseñados en el Servicio, en forma temporal o permanente, en cualquier momento, sin previo aviso y sin responsabilidad alguna. Además, la Compañía y/o los propietarios del Contenido de Ambly.co pueden, en forma ocasional, sacar el Contenido de Ambly.co del Servicio sin previo aviso, y la Compañía podrá en cualquier momento perder el derecho a poner a disposición determinado Contenido de Ambly.co. En tal caso, usted ya no podrá obtener ni ver determinado contenido. " />
                      <br />
                    </li>
                  </ol>
                </li>
                <li className="subtitle-li">
                  <Typography variant="H4" text="Propiedad intelectual." />
                  <ul>
                    <br />
                    <li>
                      <Typography variant="H6" text="Secretos comerciales y materiales de propiedad exclusiva." />
                      <Typography variant="P" text="El Servicio contiene y/o incorpora secretos comerciales, inventos patentados (y/o con patente pendiente) y / u otros materiales de propiedad exclusiva y propiedad intelectual de la Compañía y/o sus licenciadores. Todos los derechos de título y propiedad en el Servicio, incluyendo sin que signifique limitación alguna el contenido Ambly.co y cualquier copia relacionada con el Servicio y el contenido de Ambly.co permanecen bajo la propiedad de la Compañía y sus licenciadores, según corresponda. Usted conviene en mantener en forma confidencial aquella información contenida en el Servicio que no sea de dominio público, y no revelar dicha información a terceros sin la aprobación previa por escrito de la Compañía. " />
                      <br />
                      <Typography variant="P" text="Los usuarios no están autorizados para tratar de reconfigurar, descomponer o utilizar ingeniería inversa sobre la página web de Ambly.co, el Servicio y/o el Contenido de Ambly.co" />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Derechos de autor." />
                      <Typography variant="P" text='El Contenido de Ambly.co y otras obras de autoría que se encuentran en el Servicio, o forman parte del mismo (colectivamente, el "Contenido"), están protegidos por las leyes aplicables de derechos de autor y los tratados internacionales de derechos de autor, así como por otras leyes y tratados de propiedad intelectual. El Contenido se licencia, no se vende. Usted no puede realizar copias no autorizadas o utilizar ninguna parte del Contenido, salvo como se especifica en este documento y de conformidad con la legislación aplicable. Todos los títulos y derechos de autor del Contenido y del Servicio (incluyendo, entre otros, imágenes, fotografías, animaciones, vídeo, audio, código, artículos, texto y "applets", incorporados al Servicio), son propiedad de la Compañía o sus licenciadores. Usted acepta cumplir con todas las leyes aplicables sobre protección de derechos de autor en relación con el uso del Servicio y del Contenido por parte de usted. Además de lo estipulado en estos Términos de Servicio, la Compañía podrá adoptar medidas adecuadas para proteger los derechos de autor en el Contenido.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Marcas comerciales." />
                      <Typography variant="P" text='No puede utilizar ninguna de las marcas comerciales que se encuentran dentro del Servicio, salvo lo especificado en el presente y de conformidad con la legislación aplicable. No puede copiar, exhibir o utilizar ninguna de las marcas comerciales sin el permiso previo por escrito del propietario. Cualquier uso no autorizado podría violar las leyes de marcas comerciales, las leyes de privacidad y publicidad, así como las leyes civiles o penales. Las marcas que figuran a continuación son marcas registradas de la Compañía, sus casas matrices directas o indirectas, y/o sus Afiliadas, licenciadores o terceros propietarios. Nada de lo contenido en el Servicio deberá interpretarse como una concesión por impedimento o de algún otro modo, de cualquier licencia o derecho de uso de cualquier marca. Tenga en cuenta que la siguiente lista de marcas se actualiza en forma periódica. Por lo tanto, ni esta lista ni sus actualizaciones incluyen todas las marcas. En cuanto a preguntas relacionadas con cualquiera de las marcas o la siguiente lista de marcas, le rogamos que envíe sus consultas a' />
                      <br />
                      <p><b>Responsable:</b> Bortek S.AS., con domicilio en Calle 86 #20-45.,o envíe un mensaje electrónico <a href="mailto:at@ambly.co">at@ambly.co</a></p>
                      <br />
                      <Typography variant="P" text='Ambly.co, el logotipo de "Ambly.co", Ambly.co plataforma, y otras marcas comerciales utilizadas en el Servicio son marcas registradas de sus respectivos propietarios.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Derechos de la Compañía respecto a los materiales que usted publica." />
                      <Typography variant="P" text='Al enviar mensajes, opiniones, ingresar datos o participar en cualquier otra forma de comunicación a través del Servicio (si así lo permite la Compañía), usted declara que tiene todos los derechos para publicar dichos materiales, que estos no violan los derechos de terceros, y que acepta que la Compañía puede copiar, sub-licenciar, adaptar, transmitir, ejecutar públicamente o exhibir cualquiera de tales contenidos para proporcionar y/o promover el Servicio y/o responder a cualquier requisito legal, demanda o amenaza. Si el uso de tales contenidos por parte de la Compañía explota cualquier derecho de propiedad que usted pueda tener sobre dicho material, usted acepta que la Compañía tiene un derecho irrestricto, libre de regalías, no exclusivo y perpetuo de hacerlo en todo el mundo. Usted acepta que toda pérdida o daño de cualquier tipo que se produzca como consecuencia de la utilización de cualquier mensaje, contenido o material que usted carga, pública, transmite, exhibe o pone de algún modo a disposición a través del uso que usted haga del Servicio, es exclusivamente responsabilidad de usted.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Acción por infracción de los derechos de propiedad intelectual." />
                      <Typography variant="P" text='Si la Compañía recibe una notificación alegando que usted se ha involucrado en una conducta que viola cualquiera de los derechos de propiedad intelectual de la Compañía o de sus Afiliadas, o de un tercero, o razonablemente sospecha esto, la Compañía podrá suspender o dar por terminado el acceso suyo al Servicio, sin previo aviso. Si la Compañía actúa conforme a esta Sección, la misma no tendrá responsabilidad alguna frente a usted, incluso por cualquier cantidad que haya pagado previamente o cualquier crédito que tenga en el Servicio.' />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Cumplimiento con la Ley de Protección de los Derechos de Autor, en el Milenio Digital." />
                      <Typography variant="P" text='Si usted es titular de derechos de autor o un agente del mismo, y considera que los materiales enviados por algún usuario, u otros materiales que no son de la Compañía, violan sus derechos, puede enviar una notificación de conformidad con la Ley de Protección de los Derechos de Autor en el Milenio Digital (Digital Millennium Copyright Act - DMCA), facilitándole a nuestro agente de derechos de autor (que se indica abajo) la siguiente información por: (a) una firma física o electrónica de la persona autorizada para actuar en nombre del titular de un derecho exclusivo presuntamente infringido, (b) la identificación de la obra protegida por derechos de autor que, según se afirma, ha sido objeto de una infracción, o bien, si una sola notificación cubre varias obras protegidas por derechos de autor en el Servicio, una lista representativa de dichas obras en el Servicio, (c) la identificación del material que, según se afirma, infringe o es objeto de una actividad infractora y que debe eliminarse o al que debe inhabilitarse el acceso, e información razonablemente suficiente que le permita a Video Greetings localizar el material; (d) información razonablemente suficiente que le permita a Video Greetings comunicarse con la parte demandante, como una dirección, número de teléfono y, si estuviera disponible, una dirección de correo electrónico donde se pueda contactar a la parte demandante, (e) una declaración que la parte demandante cree de buena fe explicando que el uso del material en cuestión no fue autorizado por el titular de los derechos de autor, su representante o la ley, y (f) una declaración diciendo que la información incluida en la notificación es exacta y, bajo pena de perjurio, que la parte demandante está autorizada a actuar en nombre del titular de un derecho exclusivo que presuntamente se infringe. Cualquier consulta al respecto no dude en escribirnos a at@ambly.co.' />
                      <br />
                    </li>
                  </ul>
                </li>
                <li className="subtitle-li">
                  <Typography variant="H4" text="Términos estándar." />
                  <ul>
                    <li>
                      <Typography variant="H6" text="Recursos." />
                      <Typography variant="P" text="Usted acuerda que cualquier uso no autorizado del Servicio y de cualquier tecnología contenida en el mismo podría ocasionar un perjuicio irreparable a la Compañía para la cual una compensación por daños y perjuicios monetarios no sería insuficiente. Por lo tanto, en tal caso, la Compañía tendrá derecho, además de otros recursos disponibles de acuerdo al derecho y en equidad, a un desagravio por mandato judicial inmediato en contra de usted y para evitar cualquier uso no autorizado. Nada de lo contenido en esta Sección o en otra parte de estos Términos de Servicio se interpretará como que limita los recursos disponibles de conformidad con las reclamaciones legales o de otro tipo que la Compañía pueda tener bajo una autoridad jurídica independiente. Usted entiende y conviene en que la cancelación de su cuenta de Ambly.co es su único derecho y recurso con respecto a cualquier controversia con la Compañía." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Indemnización." />
                      <Typography variant="P" text="Usted conviene en defender, indemnizar y eximir de toda responsabilidad a la Compañía respecto a todas y cualesquiera reclamaciones, pérdidas, daños y perjuicios, responsabilidades, deficiencias, sentencias, gravámenes, multas, costas y otros gastos (incluidos los honorarios razonables de abogados) que surjan de o, en relación con, el uso por parte de usted del Servicio, o cualquier incumplimiento por parte de usted de estos Términos de Servicio, y conviene en rembolsar a la Compañía, a solicitud, cualquier pérdida, costo o gasto en los que incurran a causa de ello." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Plazo; terminación." />
                      <Typography variant="P" text="El plazo de estos Términos de Servicio se mantendrá en efecto hasta que se dé por terminado, según se describe en el presente. Estos Términos de Servicio y los derechos que usted tiene a acceder, descargar y utilizar el Servicio están sujetos a la terminación inmediata, sin previo aviso, (a) si usted incumple (o la Compañía sospecha razonablemente que usted ha incumplido) cualquier disposición de estos Términos de Servicio, o (b) tras la interrupción por parte de la Compañía de la difusión o apoyo del Servicio. Si dicha terminación sin previo aviso está expresamente prohibida por la legislación aplicable, entonces dicha terminación se producirá tras la notificación de cualquiera de dichos incumplimientos. Tras la terminación, usted debe dejar de utilizar el Servicio, por completo. Si la Compañía da por terminados estos Términos de Servicio, o suspende su Cuenta de Ambly.co por cualquiera de las razones expuestas en estos Términos de Servicio, la Compañía no tendrá ninguna obligación ni responsabilidad hacia usted y no le devolverá ningún importe que usted haya pagado con anterioridad." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="NOTAS LEGALES; LIMITACIÓN DE RESPONSABILIDAD." />
                      <ol>
                        <br />
                        <li>
                          <Typography variant="P" text='USTED ENTIENDE Y CONVIENE EN QUE EL USO DEL SERVICIO ES A SU EXCLUSIVO RIESGO. SALVO LO EXPRESAMENTE ESTABLECIDO EN EL PRESENTE, EL SERVICIO SE PROPORCIONA "EN EL ESTADO EN QUE SE ENCUENTRA" Y SIN GARANTÍA DE NINGÚN TIPO POR PARTE DE LA COMPAÑÍA NI DE SUS AFILIADAS, SEGÚN CORRESPONDA, Y EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY APLICABLE, LA COMPAÑÍA EXPRESAMENTE RENUNCIA A TODAS LAS GARANTÍAS, YA SEA EXPRESAS O IMPLÍCITAS, INCLUIDAS, ENTRE OTRAS, LAS GARANTÍAS IMPLÍCITAS DE COMERCIALIZACIÓN, IDONEIDAD PARA UN FIN DETERMINADO, NO INFRACCIÓN Y TÍTULO. SALVO LO EXPRESAMENTE ESTABLECIDO EN EL PRESENTE, LA COMPAÑÍA NO GARANTIZA NI HACE NINGUNA DECLARACIÓN SOBRE EL USO O LOS RESULTADOS DEL USO DEL SERVICIO CON RESPECTO AL RENDIMIENTO, PRECISIÓN, FIABILIDAD, SEGURIDAD, CAPACIDAD, ACTUALIDAD U OTROS ASPECTOS. USTED NO RESPONSABILIZARÁ A LA COMPAÑÍA NI A SUS AFILIADAS DE NINGÚN DAÑO DERIVADO DE SU ACCESO (INCLUYENDO CUALQUIER SOFTWARE O SISTEMAS QUE UTILICE PARA ACCEDER) AL SERVICIO, INCLUYENDO, SIN LIMITACIÓN, DAÑOS A CUALQUIER COMPUTADORA, SOFTWARE O SISTEMAS, O DISPOSITIVOS PORTÁTILES REGISTRADOS QUE USTED UTILICE PARA ACCEDER AL MISMO. NO SE GARANTIZA QUE EL FUNCIONAMIENTO DEL SERVICIO SEA ININTERRUMPIDO NI QUE ESTÉ EXENTO DE ERRORES. NINGUNA INFORMACIÓN O ASESORAMIENTO ORAL O ESCRITO PROPORCIONADO POR CUALQUIER PERSONA, CONSTITUIRÁ NINGÚN TIPO DE GARANTÍA EN RELACIÓN CON LA COMPAÑÍA O SUS AFILIADAS.' />
                          <br />
                        </li>
                        <li>
                          <Typography variant="P" text='LA COMPAÑÍA NO GARANTIZA QUE EL SERVICIO SEA COMPATIBLE CON CUALQUIER COMPUTADORA PERSONAL, REPRODUCTOR DE CD O DVD, GRABADOR DE CD O DVD, O DISPOSITIVOS PORTÁTILES REGISTRADOS. USTED ES EL ÚNICO RESPONSABLE DE ASEGURARSE DE QUE SUS SISTEMAS FUNCIONEN CORRECTAMENTE CON EL SERVICIO.' />
                          <br />
                        </li>
                        <li>
                          <Typography variant="P" text='EL SERVICIO PUEDE CONTENER PUNTOS DE VISTA, CONSEJOS, DECLARACIONES Y OPINIONES, QUE REPRESENTAN LAS OPINIONES, CONSEJOS, OPINIONES Y DECLARACIONES DE LOS AUTORES INDIVIDUALES y NO NECESARIAMENTE LOS DE CUALQUIER COMPAÑÍA AFILIADA. LA COMPAÑÍA NO DECLARA NI AVALA LA EXACTITUD O LA CONFIABILIDAD DE CUALQUIER PUNTO DE VISTA, CONSEJO, OPINIÓN, DECLARACIÓN U OTRA INFORMACIÓN PROPORCIONADA POR DICHOS AUTORES. DICHOS PUNTOS DE VISTA, OPINIONES, CONSEJOS, DECLARACIONES U OTRA INFORMACIÓN SON ÚNICAMENTE LOS DE LOS AUTORES Y NO PUEDEN SER ATRIBUIDOS A LA COMPAÑÍA O SUS AFILIADAS. LA CONFIANZA QUE USTED DEPOSITE EN TALES PUNTOS DE VISTA, OPINIONES, CONSEJOS, DECLARACIONES U OTRA INFORMACIÓN QUEDA TAMBIÉN BAJO SU PROPIO RIESGO. LA COMPAÑÍA NO SERÁ RESPONSABLE ANTE NADIE DE NINGUNA INEXACTITUD, ERROR, OMISIÓN, INTERRUPCIÓN, OPORTUNIDAD, INFRACCIÓN DE CUALQUIER DERECHO DE PROPIEDAD INTELECTUAL, INTEGRIDAD, ELIMINACIÓN, DEFECTO, FALLA DE FUNCIONAMIENTO, FALLA EN LAS LÍNEAS DE COMUNICACIÓN, ALTERACIÓN O USO DE LAS OBRAS DEL AUTOR, INDEPENDIENTEMENTE DE LA CAUSA, O POR CUALQUIER DAÑO QUE DE ALLÍ RESULTE. LA COMPAÑÍA NO ASUME RESPONSABILIDAD ALGUNA, y NO SERÁ RESPONSABLE DE NINGÚN DAÑO O VIRUS QUE DAÑE LA COMPUTADORA DE USTED U OTRA PROPIEDAD, DEBIDO AL ACCESO POR PARTE SUYA O AL USO DE LOS MATERIALES DEL AUTOR.' />
                          <br />
                        </li>
                        <li>
                          <Typography variant="P" text='EN NINGÚN CASO, LA COMPAÑÍA SERÁ RESPONSABLE POR DAÑOS Y PERJUICIOS DIRECTOS, EMERGENTES, EJEMPLARES, CUANTIFICABLES, INDIRECTOS, ACCESORIOS O PUNITIVOS, LUCRO CESANTE, SIN IMPORTAR SU CAUSA, QUE SURJAN DE O EN RELACIÓN CON EL SERVICIO, ESTOS TÉRMINOS DE SERVICIO O EL OBJETO DE CUALQUIERA DE LO QUE ANTECEDE, BAJO NINGUNA TEORÍA DE RESPONSABILIDAD, INCLUYENDO, ENTRE OTROS: (1) DAÑOS Y PERJUICIOS DERIVADOS DE LA PÉRDIDA DE DATOS, LUCRO CESANTE, PÉRDIDA DEL USO DEL SERVICIO Y CUALQUIER DESCARGA O CUALQUIER EQUIPO RELACIONADO, TIEMPO DE INACTIVIDAD Y TIEMPO DEL USUARIO, AUNQUE LA COMPAÑÍA Y SUS AFILIADAS HAYAN SIDO NOTIFICADAS SOBRE LA POSIBILIDAD DE TALES DAÑOS Y PERJUICIOS (2) DAÑOS Y PERJUICIOS DERIVADOS DEL USO QUE USTED HAGA DEL SERVICIO Y QUE INFRINJA ESTOS TÉRMINOS DE SERVICIO, EN PARTICULAR LAS LIMITACIONES CON RESPECTO AL USO. BAJO NINGUNA CIRCUNSTANCIA LA COMPAÑÍA O SUS AFILIADAS SERÁN RESPONSABLES POR EL USO NO AUTORIZADO DE CUALQUIER CONTENIDO O CUALQUIER USO DEL SERVICIO PARA DESARROLLAR, DISTRIBUIR O UTILIZAR CUALQUIER MATERIAL QUE SEA DIFAMATORIO, CALUMNIOSO, INJURIOSO U OBSCENO, QUE DÉ UNA FALSA IMPRESIÓN DE CUALQUIER PERSONA, QUE CONSTITUYA UNA INVASIÓN DE CUALQUIER DERECHO A LA PRIVACIDAD O UNA INFRACCIÓN DE CUALQUIER DERECHO A LA PUBLICIDAD, QUE VIOLE O INFRINJA LOS DERECHOS DE CUALQUIER TERCERO O QUE INFRINJA CUALQUIER LEY O REGULACIÓN EXTRANJERA, FEDERAL, ESTATAL O LOCAL.' />
                          <br />
                        </li>
                        <li>
                          <Typography variant="P" text='ALGUNAS JURISDICCIONES NO PERMITEN LA EXCLUSIÓN O LIMITACIÓN DE GARANTÍAS IMPLÍCITAS O DE RESPONSABILIDAD POR DAÑOS Y PERJUICIOS ACCESORIOS O EMERGENTES, DE MODO QUE ES POSIBLE QUE DICHAS EXCLUSIONES O LIMITACIONES NO SEAN APLICABLES AL CASO DE USTED. EN LA MEDIDA EN QUE EN UNA CIRCUNSTANCIA DETERMINADA, CUALQUIER NOTA LEGAL O LIMITACIÓN SOBRE DAÑOS Y PERJUICIOS O RESPONSABILIDAD AQUÍ ESTABLECIDA ESTÉ PROHIBIDA POR LA LEY APLICABLE, ENTONCES, EN LUGAR DE LAS DISPOSICIONES DEL PRESENTE EN DICHA CIRCUNSTANCIA DETERMINADA, LA COMPAÑÍA TENDRÁ DERECHO A LAS MÁXIMAS RENUNCIAS Y/O LIMITACIONES SOBRE DAÑOS Y PERJUICIOS Y LA RESPONSABILIDAD DISPONIBLES EN DERECHO Y EN EQUIDAD POR DICHA LEY APLICABLE EN TAL CIRCUNSTANCIA EN PARTICULAR. EN NINGÚN CASO TALES DAÑOS Y PERJUICIOS O LA RESPONSABILIDAD TOTAL DE LA COMPAÑÍA SUPERARÁ LOS CARGOS PAGADOS POR USTED EN LOS ÚLTIMOS 12 MESES.' />
                          <br />
                        </li>
                      </ol>
                    </li>
                    <li>
                      <Typography variant="H6" text="Elección de derecho y jurisdicción territorial." />
                      <Typography variant="P" text="Estos Términos de Servicio y el uso que usted hace del Servicio se regirán de conformidad con las leyes de Colombia, sin incluir (i) los principios de conflicto de leyes, (ii) la Convención de las Naciones Unidas sobre los Contratos de Compraventa Internacional de Mercaderías, (iii) la Convención de 1974 sobre la Prescripción en materia de Compraventa Internacional de Mercaderías, y (iv) el Protocolo que enmienda la Convención de 1974, hecho en Viena el 11 de abril de 1980. Usted conviene en que cualquier demanda o controversia con la Compañía o con cualquier Afiliada, o bien que surja de o en relación a estos Términos de Servicio, el Servicio o el uso que usted hace de cualquiera de estos, será entablada ante la jurisdicción competente en la ciudad de domicilio de la Compañía. Usted acepta someterse a la exclusiva jurisdicción y competencia territorial de estos tribunales y renunciar a cualquier objeción en cuanto a la jurisdicción, competencia territorial o tribunal inapropiado de tales tribunales. LAS PARTES NO PLANTEARÁN UNA DISPUTA EN RELACIÓN CON ESO, Y POR ESTE MEDIO RENUNCIAN A JUICIO POR JURADO Y/O A CUALQUIER DEFENSA EN RAZÓN DE LA COMPETENCIA TERRITORIAL, TRIBUNAL INAPROPIADO, LA FALTA DE JURISDICCIÓN PERSONAL, LA SUFICIENCIA DE NOTIFICACIÓN DE ACTOS PROCESALES U OTRAS RAZONES SIMILARES EN CUALQUIERA DE DICHAS ACCIONES O LITIGIOS. En la medida permitida por la ley, las disposiciones de estos Términos de Servicio remplazarán a las disposiciones del Código de Comercio Uniforme y la Ley de Transacciones Electrónicas Uniformes que adopten o apliquen al Servicio en cualquier jurisdicción competente." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Convenio total y divisibilidad." />
                      <Typography variant="P" text="Estos Términos de Servicio, la Política de Privacidad, los Términos de Compra y la autorización de pago (incluyendo cualquier modificación o revisión realizada por la Compañía a cualquiera de estos documentos) constituyen juntos el acuerdo total entre usted y la Compañía, con respecto a su objeto, y remplaza a todos los convenios y entendimientos previos y/o contemporáneos, ya sea escritos u orales, entre usted y la Compañía con respecto al objeto del presente documento. Salvo lo expresamente establecido en el presente, estos Términos de Servicio no podrán de ninguna manera ser enmendados, modificados o complementados por las partes, excepto mediante instrumento por escrito firmado por un directivo autorizado de la Compañía. Si un tribunal de jurisdicción competente determinara que una parte de estos Términos de Servicio es inválida o inexigible, el resto de estos Términos de Servicio se interpretará de modo que refleje razonablemente la intención de la Compañía. Los encabezamientos son únicamente a fines de referencia y de ningún modo definen, limitan, interpretan o describen el alcance o el contenido de dicha sección. Ninguna disposición del presente se considerará renunciada (por cualquier acto u omisión) a menos que tal renuncia se realice por escrito y esté firmada por un directivo autorizado de la Compañía. Estos Términos de Servicio serán vinculantes y redundarán en beneficio de los sucesores y cesionarios de cada parte, a condición de que usted no pueda ceder o transferir estos Términos de Servicio, en su totalidad o en parte, sin el consentimiento previo por escrito de un directivo autorizado de la Compañía." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Propietario posterior del Servicio; Fusión/adquisición de la Compañía." />
                      <Typography variant="P" text="Al utilizar el Servicio, usted acuerda que la Compañía o una de sus compañías podrán, en el momento de una fusión, adquisición o venta del Servicio, o de todos o de sustancialmente todos los activos de la Compañía, ceder sus derechos y obligaciones en relación con el Servicio a un propietario u operador aplicable posterior. En caso de dicha fusión, adquisición o venta, el uso continuado del Servicio significa su acuerdo a obligarse por el Servicio de Términos y la política de privacidad del propietario u operador posterior del Servicio." />
                      <br />
                    </li>
                    <li>
                      <Typography variant="H6" text="Supervivencia." />
                      <Typography variant="P" text='Los párrafos de estos Términos de Servicio titulados "Indemnización", "Limitación de responsabilidad", "Elección de derecho y jurisdicción", "Cargos y facturación", "Derechos de la compañía a los materiales que usted publica", "Recursos" y "Renuncias" sobrevivirán a su terminación.' />
                      <br />
                    </li>
                  </ul>
                </li>
                <li className="subtitle-li">
                  <Typography variant="H4" text="Definiciones" />
                  <ul>
                    <br />
                    <li>
                      <Typography variant="P" text='"Afiliadas" significa la Compañía y sus casas matrices directas e indirectas, agentes, empleados, licenciadores, distribuidores, socios comerciales, proveedores y afiliadas (y cada uno de los respectivos ejecutivos, directores, empleados y agentes de las entidades anteriores).'/>
                      <br />
                    </li>
                    <li>
                      <Typography variant="P" text='"Cuenta de Ambly" significa una cuenta de usuario registrada en el Servicio.'/>
                      <br />
                    </li>
                    <li>
                      <Typography variant="P" text='"Contenido de Ambly.co" significa la música, imágenes, texto y otros materiales que usted puede obtener o a los cuales puede acceder en forma digital desde el Servicio, cuyo contenido es propiedad de la Compañía o de terceros licenciadores'/>
                      <br />
                    </li>
                    <li>
                      <p>"Política de Privacidad" significa la Política de Privacidad de la Compañía que puede consultar haciendo clic en el enlace que se encuentra en la parte inferior de la página principal del Servicio, la cual podrá ser enmendada, modificada o revisada en forma ocasional por la Compañía como se indica en los términos de la <Link href="/politicas">Política de Privacidad.</Link> </p>
                      <br />
                    </li>
                    <li>
                      <Typography variant="P" text='"Información de Registro" significa la información que usted proporciona a la compañía o al Servicio cuando se registra para una cuenta de Ambly.co y durante el proceso de instalación que lleva a cabo para utilizar el Servicio (incluyendo un nombre único de miembro (usuario), una contraseña y su dirección válida de correo electrónico).'/>
                      <br />
                    </li>
                    <li>
                      <Typography variant="P" text='“Contratos de apertura y reglamento de uso” se entiende como el acuerdo mediante el cual una entidad crediticia, de ordinario un banco, se obliga a tener a disposición de una persona sumas de dinero dentro del límite pactado y por un tiempo fijo o indeterminado. Pactando su utilización mediante documento suscrito entre las partes, el cual se denominará “Reglamento de Uso”.'/>
                      <br />
                    </li>
                    <li>
                      <Typography variant="P" text='“Usuario/ estudiante” es la persona natural o jurídica que accede al servicio proporcionado en Ambly.co y que tendrá la posibilidad de aprender diversos temas de desarrollo web a través de nuestros servicios en línea (plataforma educativa, chat, streamings, etc.) y de la funcionalidad del sitio, así como fuera de línea por medio de cursos presenciales y conferencias.'/>
                      <br />
                    </li>
                  </ul>
                </li>
                <li className="subtitle-li">
                  <Typography variant="H4" text='Preguntas'/>
                  <br />
                  <p>Si tiene alguna pregunta o comentario sobre estos Términos de Servicio, no dude en contactarnos mediante la siguiente página <a target="_blank" href="https://ambly.co/ayuda">www.ambly.co/ayuda</a>  <b>Ambly.co Business and Legal Affairs (Asuntos comerciales y legales de Ambly.co)</b></p>
                  <ul>
                    <li>
                      <p><b>Bortek S.A.S.</b><br />Bogotá Calle 86 #20-45, o envíe un mensaje electrónico a <a href="mailto:at@ambly.co">at@ambly.co</a></p>
                    </li>
                  </ul>
                </li>
              </ol>
            </li> 
          </ol>   
        </div>
      </Main>
    </>
  )
}

export const getServerSideProps = withIronSessionSsr(
  getSessionVerificationNotCreated,
  sessionOptions
)
