import Head from "next/head"
import Image from "next/image"
// Assests
import ImageCourse from "../../../assets/images/new-course.jpg"
import Detail1 from "../../../assets/images/icon-detail-1.png"
import Detail2 from "../../../assets/images/icon-detail-2.png"
import Detail3 from "../../../assets/images/icon-detail-3.png"
import Detail4 from "../../../assets/images/icon-detail-4.png"
import maestra from "../../../assets/images/maestra.png"
// Styled components
import { Main } from "../../../styles/curso.styled"
// Components
import { Header, Typography, SideNav } from "../../../components"
import ImageName from "../../../assets/images/svg-ejem.png"
import { FaUserAlt } from "react-icons/fa"

const items = [1, 2, 3, 4]

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <SideNav />
        <Header />

        <div className="top">
          <Image className="image-course" src={ImageCourse} alt="" />
          <div className="overlay"></div>
          <div className="top-content">
            <Image className="image-name" src={ImageName} alt="" />
            <div className="autor">
              <FaUserAlt className="icon" />
              <span>Carlos Jaramillo</span>
            </div>
          </div>
        </div>

        <div className="content-page">
          <Typography
            className="description"
            text="Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book."
            variant="P"
          />

          <br />

          <div className="price">
            <Typography className="description" text="Precio:" variant="H6" />
            <Typography className="description" text="$30.000" variant="H2" />
          </div>

          <div className="caracteristics">
            <div className="caracteristics-item">
              <Image className="icon" src={Detail1} alt="" />
              <p>Duración</p>
              <span>4 Horas</span>
            </div>
            <div className="caracteristics-item">
              <Image className="icon" src={Detail2} alt="" />
              <p>Aprenderás</p>
              <span>Lorem Ipsum is simply</span>
            </div>
            <div className="caracteristics-item">
              <Image className="icon" src={Detail3} alt="" />
              <p>Cantidad de modulos</p>
              <span>4 modulos</span>
            </div>
            <div className="caracteristics-item">
              <Image className="icon" src={Detail4} alt="" />
              <p>Estructura</p>
              <span>Lorem Ipsum is simply</span>
            </div>
          </div>

          <div className="modulos-section">
            <Typography
              className="description"
              text="Cononce todos los módulos"
              variant="H4"
            />
            <Typography
              className="description"
              text="Lorem Ipsum is simply dummy text of the printing and typesetting industry. "
              variant="P"
            />
          </div>

          <div className="teacher-section">
            <Typography
              className="description"
              text="Cononce a tu maestro"
              variant="H4"
            />
            <Image className="avatar" src={maestra} alt="" />
            <Typography
              className="description"
              text="Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer took a galley of type
            and scrambled it to make a type specimen book."
              variant="P"
            />
            <Image className="image-teacher" src={ImageCourse} alt="" />
            <Typography
              className="description"
              text="Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s, when an unknown printer"
              variant="P"
            />
          </div>
        </div>
      </Main>
    </>
  )
}
